# -*- coding: utf-8 -*-
"""Mulesoft_Screening_Test_SAGAR S K

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a7yrkpavpfhISoAeohisWrHcWmI7HmPt

Importing sqlite3 module
"""

import sqlite3 as sq

"""Establishing connection with the database"""

connection = sq.connect("Movies_DB.db")

"""Creating a cursor to handle the queries for the database"""

cursor = connection.cursor()

"""Creating a table """

cursor.execute("CREATE TABLE IF NOT EXISTS MOVIES( NAME TEXT, ACTOR TEXT, ACTRESS TEXT,DIRECTOR_NAME TEXT, YEAR INTEGER )")

"""Inserting data to the table"""

cursor.execute("INSERT INTO MOVIES VALUES('Doctor Strange','Benedict Cumberbatch','Rachel McAdams','Scott Derrickson',2016)")
cursor.execute("INSERT INTO MOVIES VALUES('The Courier','Benedict Cumberbatch','Rachel Brosnahan','Dominic Cooke',2020)")
cursor.execute("INSERT INTO MOVIES VALUES('Tenet','John David Washington','Elizabeth Debicki','Christopher Nolan',2020)")
cursor.execute("INSERT INTO MOVIES VALUES('3 Idiots','Aamir Khan','Kareena Kapoor','Rajkumar Hirani',2009)")
cursor.execute("INSERT INTO MOVIES VALUES('PK','Aamir Khan','Anushka Sharma','Rajkumar Hirani',2014)")

"""Querying all the movies in the table"""

all_rows = cursor.execute("SELECT * FROM MOVIES").fetchall()
for i in all_rows:
  title,actor,actress,director,released_year = i
  print(f"{title}\t{actor}\t{actress}\t{director}\t{released_year}")

"""Querying based on the actor's name"""

actor_rows = cursor.execute("SELECT * FROM MOVIES WHERE ACTOR = 'Benedict Cumberbatch'").fetchall()
for i in actor_rows:
  title,actor,actress,director,released_year = i
  print(f"{title}\t{actor}\t{actress}\t{director}\t{released_year}")